from __future__ import annotations

from copy import deepcopy
from typing import Any

from pisd.core.errors import PiSDErrorCodes

STYLE_CONTROLS = [
    "theme",
    "layout_mode",
    "viewport_preset",
    "panel_size_preset",
    "density",
    "font_scale",
    "panel_gap",
    "corner_radius",
    "border_strength",
    "shadow_strength",
    "minimum_panel_width",
    "preview_aspect",
]

PANEL_API_CONTRACTS: list[dict[str, Any]] = [
    {
        "id": "system-status-panel",
        "title": "System Status",
        "group": "diagnostics",
        "purpose": "Show app version, hardware mode, service state, and latest PISD code.",
        "body": "status",
        "default_size": "standard",
        "minimum_width_px": 260,
        "responsive_behavior": "Collapse metric cards to one column on narrow screens.",
        "dangerous_action": False,
        "endpoints": [
            {"method": "GET", "path": "/api/status", "required": True, "purpose": "Read full PiSD status."},
        ],
        "safe_test": {
            "method": "GET",
            "path": "/api/status",
            "payload": None,
            "expected_codes": [PiSDErrorCodes.OK],
            "label": "panel.system_status.api",
        },
    },
    {
        "id": "camera-preview-panel",
        "title": "Camera Preview",
        "group": "camera",
        "purpose": "Display the trusted request/PIL visual stream and refresh frames.",
        "body": "cameraPreview",
        "default_size": "wide",
        "minimum_width_px": 300,
        "responsive_behavior": "Keep preview aspect ratio adjustable and fit controls below the frame on small screens.",
        "dangerous_action": False,
        "endpoints": [
            {"method": "POST", "path": "/api/camera/start", "required": True, "purpose": "Start camera service."},
            {"method": "GET", "path": "/api/camera/frame.jpg", "required": True, "purpose": "Fetch one cached JPEG frame."},
            {"method": "GET", "path": "/video_feed", "required": True, "purpose": "Display the max-FPS MJPEG live stream."},
            {"method": "GET", "path": "/api/camera/fps-stats", "required": True, "purpose": "Read measured capture/encode FPS statistics."},
        ],
        "safe_test": {
            "method": "POST",
            "path": "/api/camera/start",
            "payload": {},
            "expected_codes": [PiSDErrorCodes.OK],
            "label": "panel.camera_preview.api",
        },
    },
    {
        "id": "camera-settings-panel",
        "title": "Camera Settings",
        "group": "camera",
        "purpose": "Test size, quality, exposure, WB, buffer, transform, and image tuning controls.",
        "body": "cameraSettings",
        "default_size": "large",
        "minimum_width_px": 320,
        "responsive_behavior": "Use two-column forms on wide panels and one-column forms on phones.",
        "dangerous_action": False,
        "endpoints": [
            {"method": "GET", "path": "/api/camera/config", "required": True, "purpose": "Read camera settings."},
            {"method": "GET", "path": "/api/camera/capabilities", "required": False, "purpose": "Read Picamera2 capabilities when available."},
            {"method": "GET", "path": "/api/camera/fps-stats", "required": False, "purpose": "Read live frame FPS and encode metrics."},
            {"method": "POST", "path": "/api/camera/apply", "required": True, "purpose": "Apply camera settings."},
        ],
        "safe_test": {
            "method": "POST",
            "path": "/api/camera/apply",
            "payload": {"width": 426, "height": 240, "preview_quality": 65, "capture_source": "request", "array_color_order": "rgb"},
            "expected_codes": [PiSDErrorCodes.OK],
            "label": "panel.camera_settings.api",
        },
    },
    {
        "id": "motor-settings-panel",
        "title": "Motor Settings",
        "group": "motor",
        "purpose": "Adjust per-car direction, speed limits, bias, and steering mix without moving wheels.",
        "body": "motorSettings",
        "default_size": "standard",
        "minimum_width_px": 300,
        "responsive_behavior": "Keep direction and speed-limit fields readable on touch screens.",
        "dangerous_action": False,
        "endpoints": [
            {"method": "GET", "path": "/api/motor/config", "required": True, "purpose": "Read current motor settings."},
            {"method": "POST", "path": "/api/motor/apply", "required": True, "purpose": "Apply motor settings without movement."},
        ],
        "safe_test": {
            "method": "POST",
            "path": "/api/motor/apply",
            "payload": {"left_direction": 1, "right_direction": 1, "steering_direction": 1, "steer_mix": 1.0},
            "expected_codes": [PiSDErrorCodes.OK],
            "label": "panel.motor_settings.api",
        },
    },
    {
        "id": "motor-channel-panel",
        "title": "Motor Channel Calibration",
        "group": "motor",
        "purpose": "Test left/right motors one by one with direction, speed, duration, and safe arming.",
        "body": "motorChannel",
        "default_size": "standard",
        "minimum_width_px": 300,
        "responsive_behavior": "Keep arming, side, direction, speed, duration, and stop controls visible together.",
        "dangerous_action": True,
        "danger_note": "Danger: real output must be armed by the user and wheels must be lifted.",
        "endpoints": [
            {"method": "POST", "path": "/api/motor/test-channel", "required": True, "purpose": "Test one motor channel."},
            {"method": "POST", "path": "/api/control/stop", "required": True, "purpose": "Stop immediately after each channel test."},
        ],
        "safe_test": {
            "method": "POST",
            "path": "/api/motor/test-channel",
            "payload": {"side": "left", "direction": 1, "speed": 0.12, "duration": 0.05, "enable_motor_output": False},
            "expected_codes": [PiSDErrorCodes.OK, PiSDErrorCodes.MOTOR_TEST_UNARMED],
            "label": "panel.motor_channel.safe_refusal_or_sim_ok",
        },
    },
    {
        "id": "manual-drive-panel",
        "title": "Manual Drive",
        "group": "control",
        "purpose": "Low-speed bench control for forward, reverse, left, right, and stop commands.",
        "body": "manualDrive",
        "default_size": "compact",
        "minimum_width_px": 260,
        "responsive_behavior": "Keep STOP central and reachable; collapse joystick to stacked buttons on very narrow screens.",
        "dangerous_action": True,
        "danger_note": "Danger: final GUI should add explicit motor arming before non-zero commands.",
        "endpoints": [
            {"method": "POST", "path": "/api/control/manual", "required": True, "purpose": "Send steering/throttle command."},
            {"method": "POST", "path": "/api/control/stop", "required": True, "purpose": "Emergency stop."},
        ],
        "safe_test": {
            "method": "POST",
            "path": "/api/control/manual",
            "payload": {"steering": 0.0, "throttle": 0.0, "steer_mix": 1.0},
            "expected_codes": [PiSDErrorCodes.OK],
            "label": "panel.manual_drive.zero_command",
        },
    },
    {
        "id": "safety-stop-panel",
        "title": "Safety Stop",
        "group": "safety",
        "purpose": "Always-visible emergency stop, motor-lock state, and safety reminders.",
        "body": "safetyStop",
        "default_size": "compact",
        "minimum_width_px": 240,
        "responsive_behavior": "Must remain visible in all tested layouts and be large enough for touch use.",
        "dangerous_action": False,
        "endpoints": [
            {"method": "POST", "path": "/api/control/stop", "required": True, "purpose": "Stop all motor output."},
        ],
        "safe_test": {
            "method": "POST",
            "path": "/api/control/stop",
            "payload": {},
            "expected_codes": [PiSDErrorCodes.OK],
            "label": "panel.safety_stop.api",
        },
    },
    {
        "id": "error-monitor-panel",
        "title": "Error Monitor",
        "group": "diagnostics",
        "purpose": "Show recent app, camera, and motor error codes with clear/refresh actions.",
        "body": "errors",
        "default_size": "standard",
        "minimum_width_px": 300,
        "responsive_behavior": "Use wrapping code chips and scrollable history when many errors exist.",
        "dangerous_action": False,
        "endpoints": [
            {"method": "GET", "path": "/api/errors", "required": True, "purpose": "Read recent error history."},
            {"method": "POST", "path": "/api/errors/clear", "required": True, "purpose": "Clear error history."},
        ],
        "safe_test": {
            "method": "GET",
            "path": "/api/errors",
            "payload": None,
            "expected_codes": [PiSDErrorCodes.OK],
            "label": "panel.error_monitor.api",
        },
    },
    {
        "id": "api-inspector-panel",
        "title": "API Inspector",
        "group": "diagnostics",
        "purpose": "Send custom GET/POST requests and verify response codes before wiring final controls.",
        "body": "apiInspector",
        "default_size": "large",
        "minimum_width_px": 320,
        "responsive_behavior": "Keep request builder and response body stacked on narrow screens.",
        "dangerous_action": False,
        "endpoints": [
            {"method": "GET", "path": "/api/test-gui/manifest", "required": True, "purpose": "Read testing GUI manifest."},
            {"method": "GET", "path": "/api/panel-testing/manifest", "required": True, "purpose": "Read panel manifest and contracts."},
        ],
        "safe_test": {
            "method": "GET",
            "path": "/api/panel-testing/manifest",
            "payload": None,
            "expected_codes": [PiSDErrorCodes.OK],
            "label": "panel.api_inspector.manifest",
        },
    },
    {
        "id": "validation-panel",
        "title": "Validation Checklist",
        "group": "testing",
        "purpose": "Expose simple checks for panel health, responsive behaviour, and local API status.",
        "body": "validation",
        "default_size": "standard",
        "minimum_width_px": 300,
        "responsive_behavior": "Checklist should stay readable with long OK/FAIL lines.",
        "dangerous_action": False,
        "endpoints": [
            {"method": "GET", "path": "/api/status", "required": True, "purpose": "Read status for validation baseline."},
            {"method": "GET", "path": "/api/panel-testing/manifest", "required": True, "purpose": "Read panel contract map."},
        ],
        "safe_test": {
            "method": "GET",
            "path": "/api/status",
            "payload": None,
            "expected_codes": [PiSDErrorCodes.OK],
            "label": "panel.validation.status",
        },
    },
    {
        "id": "recording-panel",
        "title": "Recording and Dataset",
        "group": "future",
        "purpose": "Reserve final GUI space for frame capture, steering labels, sessions, and dataset export.",
        "body": "placeholder",
        "default_size": "compact",
        "minimum_width_px": 280,
        "responsive_behavior": "Future recording controls should not hide STOP or live camera status.",
        "dangerous_action": False,
        "future_placeholder": True,
        "endpoints": [],
        "safe_test": {
            "method": "NONE",
            "path": "",
            "payload": None,
            "expected_codes": [PiSDErrorCodes.TEST_PANEL_CONTRACT_SKIPPED],
            "label": "panel.recording.placeholder",
        },
    },
    {
        "id": "model-runtime-panel",
        "title": "Model and Lane Runtime",
        "group": "future",
        "purpose": "Reserve final GUI space for model loading, lane detection, and autonomous runtime status.",
        "body": "placeholder",
        "default_size": "compact",
        "minimum_width_px": 280,
        "responsive_behavior": "Future AI/lane controls should remain isolated from manual safety controls.",
        "dangerous_action": False,
        "future_placeholder": True,
        "endpoints": [],
        "safe_test": {
            "method": "NONE",
            "path": "",
            "payload": None,
            "expected_codes": [PiSDErrorCodes.TEST_PANEL_CONTRACT_SKIPPED],
            "label": "panel.model_runtime.placeholder",
        },
    },
]


def get_panel_contracts() -> list[dict[str, Any]]:
    """Return a deep copy so callers can safely annotate contract data."""
    return deepcopy(PANEL_API_CONTRACTS)


def build_panel_testing_manifest(version: str) -> dict[str, Any]:
    panels = get_panel_contracts()
    return {
        "app": "PiSD",
        "version": version,
        "code": PiSDErrorCodes.OK,
        "message": "Panel testing GUI manifest and API contract map loaded.",
        "page": "/panel-testing",
        "static_base": "/testing/static/",
        "design_rules": [
            "Panels are rebuilt for the new panel lab rather than copied from older testing GUI panels.",
            "Panels must remain flexible across phone, tablet, laptop, and large-monitor layouts.",
            "Panel style, size, density, spacing, radius, border, shadow, and preview aspect must be testable from the page.",
            "Each panel must declare its API contract before final GUI wiring.",
            "Real motor output remains locked unless an explicit hardware test arms it.",
        ],
        "panel_count": len(panels),
        "panels": panels,
        "style_controls": list(STYLE_CONTROLS),
        "contract_rules": {
            "safe_mode_default": True,
            "future_placeholders_use_code": PiSDErrorCodes.TEST_PANEL_CONTRACT_SKIPPED,
            "contract_failure_code": PiSDErrorCodes.TEST_PANEL_API_CONTRACT_FAILED,
            "motor_output_default": "locked",
            "dangerous_actions_require_explicit_arming": True,
        },
    }
